project:
  type: website
  output-dir: docs
  render:
    - docs-src/*.qmd

website:
  navbar:
    left:
      - text: Home
        href: docs-src/index.qmd
      - text: Create SE
        href: docs-src/create-se-file.qmd
      - text: Genome Annotations
        href: docs-src/create-genome-annotations.qmd

format:
  html:
    theme: cosmo
    toc: true