services:
  shiny:
    image: ghcr.io/KLemonLab/contento:latest
    container_name: contento
    ports:
      - "3838:3838"
    volumes:
      - ./inst:/srv/shiny-server/app/inst
    environment:
      - SHINY_PORT=3838
    restart: unless-stopped
