project:
  type: website
  output-dir: ../docs
  render:
    - "*.qmd"
  
website:
  title: "<strong>CONTENTO</strong>"
  
  navbar:
    right:
      - icon: github
        href: https://github.com/KLemonLab/CONTENTO
        aria-label: GitHub

      - text: Lemon Lab
        href: https://www.bcm.edu/research/faculty-labs/katherine-lemon-lab

  sidebar:
    style: docked
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Installation

      - section: Input Files
        contents:
          - href: create-se-file.qmd
            text: SE File
          - href: create-genome-annotations.qmd
            text: Genome Annotations

format:
  html:
    theme: yeti
    toc: true
    toc-location: right
    page-layout: full