project:
  type: website
  output-dir: ../docs
  render:
    - "*.qmd"

website:
  title: "CONTENTO Documentation"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Create SE
        href: create-se-file.qmd
      - text: Genome Annotations
        href: create-genome-annotations.qmd

format:
  html:
    theme: cosmo
    toc: true